spring:
  application:
    name: booking

  datasource:
    url: jdbc:mysql://localhost:3306/touristdb
    username: namrata
    password: namrata
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics

  endpoint:
    health:
      show-details: always