spring.application.name=booking
spring.datasource.url=jdbc:mysql://localhost:3306/touristdb
spring.datasource.username=namrata
spring.datasource.password=namrata

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true